import { defineField, defineType } from "sanity";

export const homePageType = defineType({
  name: "homePage",
  title: "Ana Sayfa",
  type: "document",
  groups: [
    { name: "about", title: "Hakkımızda Bölümü" },
    { name: "campaigns", title: "Kampanyalar Bölümü" },
    { name: "events", title: "Etkinlikler Bölümü" },
    { name: "stores", title: "Mağazalar Bölümü" },
    { name: "dining", title: "Yeme-İçme Bölümü" },
    { name: "cinema", title: "Sinema Bölümü" },
    { name: "map", title: "Kat Planı Bölümü" },
    { name: "visit", title: "Ziyaret Bilgileri" },
    { name: "seo", title: "SEO Ayarları" },
  ],
  fields: [
    // About Section
    defineField({
      name: "aboutTag",
      title: "Hakkımızda Bölüm Etiketi (Opsiyonel)",
      type: "localizedString",
      group: "about",
      description: "Hakkımızda başlığının hemen üstünde küçük harflerle ve aralıklı görünen kategori veya etiket yazısıdır. (Örn: HAKKIMIZDA, AVLU34 AVM)",
    }),
    defineField({
      name: "aboutTitle",
      title: "Hakkımızda Başlık",
      type: "localizedString",
      group: "about",
      description: "Hakkımızda bölümünün ana başlığıdır. Büyük, şık ve zarif bir serif yazı tipiyle gösterilir. (Örn: AVLU34'E HOŞ GELDİNİZ)",
      initialValue: { tr: "AVLU34'e Hoş Geldiniz", en: "Welcome to AVLU34" },
    }),
    defineField({
      name: "aboutSubtitle",
      title: "Hakkımızda Alt Başlık",
      type: "localizedText",
      group: "about",
      description: "Ana başlığın hemen altında yer alan, kısa açıklama veya slogan niteliğindeki alt başlıktır.",
    }),
    defineField({
      name: "aboutText",
      title: "Hakkımızda Tanıtım Yazısı",
      type: "localizedBlock",
      group: "about",
      description: "Hakkımızda bölümünün merkezinde yer alan, AVM'yi tanıtan detaylı açıklama metnidir. Zengin metin editörü (bold, italik vb.) destekler.",
    }),
    defineField({
      name: "aboutImage",
      title: "Hakkımızda Görseli",
      type: "image",
      group: "about",
      options: { hotspot: true },
      description: "Bölümün sol tarafında, ekranı tam kaplayan (full-bleed) biçimde gösterilecek ana tanıtım görselidir. [İdeal Oran: 4:5 veya 3:4 Dikey Portre - Önerilen Boyut: 1000x1200px veya 1200x1500px]",
      fields: [
        {
          name: "alt",
          type: "string",
          title: "Alt Açıklama",
          description: "Görselin ne içerdiğini belirten kısa metin. Arama motorları (SEO) ve ekran okuyucular için doldurulması zorunludur.",
          validation: (Rule) => Rule.required(),
        },
      ],
    }),
    defineField({
      name: "aboutCtaLabel",
      title: "Daha Fazla Buton Metni",
      type: "localizedString",
      group: "about",
      description: "Detaylı hakkımızda sayfasına yönlendiren geniş alt çizgisiz çerçevenin içindeki buton yazısıdır. (Örn: DEVAMINI OKU)",
      initialValue: { tr: "Devamını Oku", en: "Read More" },
    }),

    // Campaigns Section
    defineField({
      name: "campaignsTitle",
      title: "Kampanyalar Başlık",
      type: "localizedString",
      group: "campaigns",
      description: "Kampanyalar & Etkinlikler (What's On) bölümünün merkezinde büyük harflerle yer alan ana başlığıdır. (Örn: KAMPANYALAR & ETKİNLİKLER)",
      initialValue: { tr: "Güncel Kampanyalar", en: "Current Offers" },
    }),
    defineField({
      name: "campaignsSubtitle",
      title: "Kampanyalar Alt Başlık",
      type: "localizedText",
      group: "campaigns",
      description: "Kampanyalar & Etkinlikler ana başlığının hemen altında ortalanmış şekilde görünen açıklama veya alt başlıktır.",
    }),
    defineField({
      name: "campaignsImage",
      title: "Kampanya Tanıtım Görseli",
      type: "image",
      group: "campaigns",
      options: { hotspot: true },
      description: "Bölümün en altında yer alan tam genişlikteki (teaser/Whats New) afiş görselidir. [İdeal Oran: 21:9 veya 16:7 Geniş Ekran / Sinematik - Önerilen Boyut: 1920x840px veya 1920x640px]",
      fields: [
        {
          name: "alt",
          type: "string",
          title: "Alt Açıklama",
          description: "Afiş görselinin ne ile ilgili olduğunu belirten arama motoru (SEO) açıklamasıdır.",
          validation: (Rule) => Rule.required(),
        },
      ],
    }),
    defineField({
      name: "campaignsCtaLabel",
      title: "Kampanyalar Buton Metni",
      type: "localizedString",
      group: "campaigns",
      description: "Kullanıcıyı kampanyalar sayfasına yönlendiren birinci butonun üzerindeki yazıdır. (Örn: KAMPANYALARI GÖR)",
      initialValue: { tr: "Kampanyaları Gör", en: "View Offers" },
    }),

    // Events Section
    defineField({
      name: "eventsTitle",
      title: "Etkinlikler Başlık",
      type: "localizedString",
      group: "events",
      description: "Etkinlikler için ayrılan alternatif başlık alanıdır. Genellikle ana Kampanyalar başlığı ile birleştirilerek tek alanda gösterilir.",
      initialValue: { tr: "Eğlenceli Etkinlikler", en: "Exciting Events" },
    }),
    defineField({
      name: "eventsSubtitle",
      title: "Etkinlikler Alt Başlık",
      type: "localizedText",
      group: "events",
      description: "Etkinlikler alternatif başlığının altındaki ek açıklama metnidir.",
    }),
    defineField({
      name: "eventsImage",
      title: "Etkinlik Tanıtım Görseli",
      type: "image",
      group: "events",
      options: { hotspot: true },
      description: "Kampanya afiş görseli girilmemişse, onun yerine alttaki büyük teaser afiş alanında kullanılacak olan yedek afiş görselidir. [İdeal Oran: 21:9 veya 16:7 Geniş Ekran - Önerilen Boyut: 1920x840px]",
      fields: [
        {
          name: "alt",
          type: "string",
          title: "Alt Açıklama",
          description: "Etkinlik afiş görselinin arama motoru (SEO) alt açıklamasıdır.",
          validation: (Rule) => Rule.required(),
        },
      ],
    }),
    defineField({
      name: "eventsCtaLabel",
      title: "Etkinlikler Buton Metni",
      type: "localizedString",
      group: "events",
      description: "Kullanıcıyı etkinlikler listesi sayfasına yönlendiren ikinci butonun üzerindeki yazıdır. (Örn: ETKİNLİKLERİ GÖR)",
      initialValue: { tr: "Etkinlikleri Gör", en: "View Events" },
    }),

    // Stores Section (Mağazalar)
    defineField({
      name: "storesTag",
      title: "Mağazalar Bölüm Etiketi",
      type: "localizedString",
      group: "stores",
      description: "Sol bloktaki mağazalar görselinin üzerinde, sol alt köşede yer alan küçük kategori etiketidir. (Örn: ALIŞVERİŞ, MAĞAZALAR)",
      initialValue: { tr: "ALIŞVERİŞ", en: "SHOP" },
    }),
    defineField({
      name: "storesTitle",
      title: "Mağazalar Başlık",
      type: "localizedString",
      group: "stores",
      description: "Sol blokta yer alan mağazalar görselinin üzerindeki ana başlık yazısıdır. (Örn: MARKALARIMIZ)",
      initialValue: { tr: "Mağazalarımız", en: "Our Stores" },
    }),
    defineField({
      name: "storesSubtitle",
      title: "Mağazalar Alt Başlık",
      type: "localizedText",
      group: "stores",
      description: "Mağazalar başlığının hemen altında yer alan ek detay veya açıklama yazısıdır.",
    }),
    defineField({
      name: "storesImage",
      title: "Mağazalar Bölüm Görseli",
      type: "image",
      group: "stores",
      options: { hotspot: true },
      description: "Mağazalar (Alışveriş) bloğunun arka planında gösterilecek olan görseldir. [İdeal Oran: 4:5 veya 3:4 Dikey - Önerilen Boyut: 1000x1200px veya 1200x1500px]",
      fields: [
        {
          name: "alt",
          type: "string",
          title: "Alt Açıklama",
          description: "Mağazalar arka plan görselinin arama motoru (SEO) açıklamasıdır.",
          validation: (Rule) => Rule.required(),
        },
      ],
    }),
    defineField({
      name: "storesCtaLabel",
      title: "Mağazalar Buton Metni",
      type: "localizedString",
      group: "stores",
      description: "Mağazalar bloğundaki beyaz çerçeveli butonun üzerindeki yazıdır. (Örn: MARKALARI GEZ)",
      initialValue: { tr: "MARKALARI GEZ", en: "EXPLORE BRANDS" },
    }),

    // Dining Section (Yeme-İçme)
    defineField({
      name: "diningTag",
      title: "Yeme-İçme Bölüm Etiketi",
      type: "localizedString",
      group: "dining",
      description: "Sağ bloktaki yeme-içme görselinin üzerinde, sol alt köşede yer alan küçük kategori etiketidir. (Örn: LEZZET, YEME-İÇME)",
      initialValue: { tr: "LEZZET", en: "DINE" },
    }),
    defineField({
      name: "diningTitle",
      title: "Yeme-İçme Başlık",
      type: "localizedString",
      group: "dining",
      description: "Sağ blokta yer alan yeme-içme görselinin üzerindeki ana başlık yazısıdır. (Örn: LEZZET NOKTALARI)",
      initialValue: { tr: "Lezzet Noktaları", en: "Dining & Cafes" },
    }),
    defineField({
      name: "diningSubtitle",
      title: "Yeme-İçme Alt Başlık",
      type: "localizedText",
      group: "dining",
      description: "Yeme-içme başlığının hemen altında yer alan ek detay veya açıklama yazısıdır.",
    }),
    defineField({
      name: "diningImage",
      title: "Yeme-İçme Bölüm Görseli",
      type: "image",
      group: "dining",
      options: { hotspot: true },
      description: "Yeme-içme bloğunun arka planında gösterilecek olan görseldir. [İdeal Oran: 4:5 veya 3:4 Dikey - Önerilen Boyut: 1000x1200px veya 1200x1500px]",
      fields: [
        {
          name: "alt",
          type: "string",
          title: "Alt Açıklama",
          description: "Yeme-içme arka plan görselinin arama motoru (SEO) açıklamasıdır.",
          validation: (Rule) => Rule.required(),
        },
      ],
    }),
    defineField({
      name: "diningCtaLabel",
      title: "Yeme-İçme Buton Metni",
      type: "localizedString",
      group: "dining",
      description: "Yeme-içme bloğundaki beyaz çerçeveli butonun üzerindeki yazıdır. (Örn: LEZZETLERİ KEŞFET)",
      initialValue: { tr: "LEZZETLERİ KEŞFET", en: "EXPLORE DINING" },
    }),

    // Cinema Section (Sinema)
    defineField({
      name: "cinemaTag",
      title: "Sinema Bölüm Etiketi",
      type: "localizedString",
      group: "cinema",
      description: "Sinema afiş/banner alanının sol alt köşesinde, başlığın üstünde küçük harflerle görünen kategori etiketidir. (Örn: SİNEMA / EĞLENCE)",
      initialValue: { tr: "SİNEMA / EĞLENCE", en: "ENTERTAIN" },
    }),
    defineField({
      name: "cinemaTitle",
      title: "Sinema Başlık",
      type: "localizedString",
      group: "cinema",
      description: "Sinema banner alanında yer alan büyük başlık yazısıdır. (Örn: AVLU34 SİNEMA DENEYİMİ)",
      initialValue: { tr: "AVLU34 Sinema", en: "AVLU34 Cinema" },
    }),
    defineField({
      name: "cinemaSubtitle",
      title: "Sinema Alt Başlık",
      type: "localizedText",
      group: "cinema",
      description: "Sinema başlığının hemen altında yer alan ek detay, vizyondaki filmler açıklaması veya slogan yazısıdır.",
    }),
    defineField({
      name: "cinemaImage",
      title: "Sinema Bölüm Görseli",
      type: "image",
      group: "cinema",
      options: { hotspot: true },
      description: "Sinema bölümünün arka planında tam genişlikte (banner) gösterilecek görseldir. [İdeal Oran: 21:9 veya 16:7 Geniş Ekran - Önerilen Boyut: 1920x800px veya 1920x600px]",
      fields: [
        {
          name: "alt",
          type: "string",
          title: "Alt Açıklama",
          description: "Sinema arka plan görselinin arama motoru (SEO) açıklamasıdır.",
          validation: (Rule) => Rule.required(),
        },
      ],
    }),
    defineField({
      name: "cinemaCtaLabel",
      title: "Sinema Buton Metni",
      type: "localizedString",
      group: "cinema",
      description: "Sinema bölümündeki beyaz çerçeveli butonun üzerindeki yazıdır. (Örn: SALONLARI İNCELE)",
      initialValue: { tr: "SALONLARI İNCELE", en: "EXPLORE CINEMA" },
    }),

    // Floor Plan Section
    defineField({
      name: "mapTitle",
      title: "Kat Planı Başlık",
      type: "localizedString",
      group: "map",
      description: "Kat Planı bölümünün başlık yazısıdır.",
      initialValue: { tr: "AVM Kat Planı", en: "Mall Directory" },
    }),
    defineField({
      name: "mapSubtitle",
      title: "Kat Planı Alt Başlık",
      type: "localizedText",
      group: "map",
      description: "Kat Planı başlığının hemen altında gösterilecek olan açıklama yazısıdır.",
    }),

    // Visit Section
    defineField({
      name: "visitTitle",
      title: "Ziyaret Başlık",
      type: "localizedString",
      group: "visit",
      description: "Ulaşım ve ziyaret bilgilerinin yer aldığı bölümün başlık yazısıdır. (Örn: ULAŞIM & ÇALIŞMA SAATLERİ)",
      initialValue: { tr: "Ziyaretinizi Planlayın", en: "Plan Your Visit" },
    }),
    defineField({
      name: "visitSubtitle",
      title: "Ziyaret Alt Başlık",
      type: "localizedText",
      group: "visit",
      description: "Ziyaret planı başlığının hemen altında gösterilecek olan ek açıklama veya karşılama yazısıdır.",
    }),
    defineField({
      name: "visitImage",
      title: "Ziyaret Bölümü Görseli",
      type: "image",
      group: "visit",
      options: { hotspot: true },
      description: "Ziyaret planı bölümünün sol tarafında tam kaplama (full-bleed) gösterilecek görseldir. AVM dış cephe veya prestijli iç mekan fotoğrafı olması önerilir. [İdeal Oran: 4:5 veya 3:4 Dikey - Önerilen Boyut: 1000x1200px veya 1200x1500px]",
      fields: [
        {
          name: "alt",
          type: "string",
          title: "Alt Açıklama",
          description: "Görselin SEO alt açıklamasıdır. (Örn: AVLU34 AVM Dış Cephe)",
          validation: (Rule) => Rule.required(),
        },
      ],
    }),
    defineField({
      name: "visitCtaLabel",
      title: "Ziyaret Buton Metni",
      type: "localizedString",
      group: "visit",
      description: "Kullanıcıyı detaylı Ziyaret Planı sayfasına yönlendiren butonun üzerindeki yazıdır. (Örn: ULAŞIM VE BİLGİLER)",
      initialValue: { tr: "ULAŞIM VE BİLGİLER", en: "EXPLORE ACCESS" },
    }),

    // SEO
    defineField({
      name: "seo",
      title: "SEO Ayarları",
      type: "seo",
      group: "seo",
      description: "Ana Sayfa için Google ve diğer arama motorlarında görünecek meta başlık (title), meta açıklama (description) ve anahtar kelime tanımlamalarıdır.",
    }),
  ],
});
